### ISSUE TITLE
Refactor to fit new lesson structure

### ISSUE THREAD

**Issue by pletcher** [learn-co-curriculum/js-ajax-callbacks-readme#14]

**Comment by pletcher** [comment]
Thanks for opening this issue!

Keep in mind that this space is for specific issues related to the _content_ of this lesson. If you'd like to report a bug about the Learn IDE, the Ask a Question form, opening a file, or the lights not working on Learn, please report a bug directly on https://learn.co. (You can find the bug report form by clicking on your avatar in the upper right, and then selecting "Report A Bug".)

Please be sure to include steps to reproduce (be as detailed as possible) and any relevant information about your environment. (Are you using the Learn IDE? Coding on a refurbished toaster?) We'll be sure to figure out what's going on — and to jump in and help — just as soon as we can. Thanks!

**Comment by scottcreynolds** [comment]
@pletcher can you give me a brief idea of what this issue and #15 require to be complete for this one?

**Comment by pletcher** [comment]
I think mostly the `html/` directory and `index.html` file seem weird to me -- we should probably stick to the flatter structure that we've been using in newer labs.

There's also some stuff that could be updated/improved, like including jQuery in `<head>` in an example (we should move that to the bottom of `<body>`).

We should also address the issues in #13 -- but so mostly it seems like a light facelift :)

**Comment by scottcreynolds** [comment]
@pletcher looks like it needs to be derubified too. got it. thanks!
