### ISSUE TITLE
Lesson not picking up my GitHub Fork

### ISSUE THREAD

**Issue by f3mshep** [learn-co-curriculum/js-ajax-callbacks-readme#24]
I forked this lesson which is a readme. It does not have any tests, but I need to fork the lesson and submit a pull request. Even though I was able to fork  the lesson, learn.co seems to not realize this fact. This issue has happened multiple times. I have tried refreshing the page, opening a new tab, clearing the cache, using a different browser, using a different PC and using a different operating system.

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @f3mshep.

We have updated the settings to prevent this lesson from requiring a pull request and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
